### ISSUE TITLE
Folder Image in PX4 Example Lab 3 is incorrect

### ISSUE THREAD

**Issue by DDeano9** [NXPHoverGames/GitBook-HoverGames#3]
There is an image on example lab 3 of the documentation that is slightly incorrect. The image that shows the 'Firmware/src/examples/' directory should have an hg_led folder in the image instead of hg_gyro (and hg_led.c instead of hg_gyro.c). It is a minor typo, but could be confusing for someone. The incorrect asset is 
GitBook-HoverGames/.gitbook/assets/image (164).png

**Comment by jarivanewijk** [comment]
Thank you for reporting this. It was fixed yesterday (thanks @landonh12)!
